partyA = set(['Park', 'Kim', 'Lee'])
partyB = set(['Park', '길동', '몽룡'])

print(f'파티에 참석한 모든 사람 {partyA | partyB}')
print('-------------------------------------------------------')
print(f'2개의 파티에 모두 참석한 사람 모든 사람 {partyA & partyB}')
print('-------------------------------------------------------')
print(f'파티 A에만 참석한 사람 {partyA - partyB}')
print('-------------------------------------------------------')
print(f'파티 B에만 참석한 사람 {partyB - partyA}')